apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: buildah-assignment-pipeline
spec:
  params:
    - name: image-repo
      type: string
      description: Docker image name
    - name: app-name
      type: string
      description: the name of the app
  workspaces:
  - name: pipeline-shared-data #where to put git repository
  tasks:

# git clone


  - name: clone-repository
    taskRef:
      kind: ClusterTask
      name: git-clone
    workspaces:
    - name: output
      workspace: pipeline-shared-data
    params:
    - name: url
      #remember to fork you acount inside github
      value: https://github.com/davidescaraggi/Davide-Will-Zoe-buildah.git


# NPM test execution

  - name: run-tests
    taskRef:
      name: npm
    workspaces:
    - name: source
      workspace: pipeline-shared-data
    params:
    - name: ARGS
      value:
      - install-ci-test
    runAfter:
      - clone-repository

# creazione build

  - name: build-image
    taskRef:
      kind: ClusterTask
      name: buildah
    runAfter:
      - run-tests
    params:
    - name: IMAGE
      value: "quay.io/davidescaraggi/buildah-assignment:$(tasks.clone-repository.results.commit)"
    workspaces:
    - name: source
      workspace: pipeline-shared-data
